import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { q } from "../db.js";
import { runFactCheck } from "../factcheck.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const SLUG = "lu-residential-q1-2026";
const TITLE = "Rapport de marché immobilier résidentiel — T1 2026";

// Runs once, at first boot (when data/reports.json has no reports yet):
//  1. Imports the originally-supplied report verbatim as published v1 ("first final report").
//  2. Runs the same AI fact-check pipeline the in-app "Run fact-check" button uses, to produce
//     the seeded v2 draft - so the very first draft is generated by the exact mechanism the app
//     will keep using for every future refresh, not a one-off manual pass.
// If step 2 fails (most likely: no GEMINI_API_KEY configured yet), v1 is still seeded and the
// server still starts; a person can click "Run fact-check" from the UI once a key is set.
export async function seedIfEmpty() {
  if (q.listReports.all().length) return;

  const original = fs.readFileSync(path.join(__dirname, "report-v1-original.html"), "utf8");

  q.createReport.run({ slug: SLUG, title: TITLE });
  const v1 = q.addVersion.run(SLUG, {
    html: original,
    status: "published",
    note: "Original report as supplied.",
    fact_check: null,
    source: "import",
    author: "seed",
  });
  console.log(`[seed] imported "${TITLE}" as published v${v1.n}`);

  try {
    console.log("[seed] running initial fact-check to seed the first draft (calls Gemini)...");
    const { html, ledger } = await runFactCheck(original);
    const v2 = q.addVersion.run(SLUG, {
      html,
      status: "draft",
      note: "Fact-checked draft — pending review.",
      fact_check: ledger,
      source: "fact-check",
      author: "system",
    });
    console.log(`[seed] seeded fact-checked draft v${v2.n} (${ledger.length} ledger entries)`);
  } catch (e) {
    console.warn(`[seed] initial fact-check skipped: ${e.message}`);
    console.warn('[seed] set GEMINI_API_KEY in .env, then use "Run fact-check" in the app to generate the first draft.');
  }
}
